# Generated by Django 3.1.14 on 2023-12-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('streetaddress', models.CharField(max_length=100)),
                ('streetaddress1', models.CharField(max_length=100)),
                ('towncity', models.CharField(max_length=100)),
                ('postcodezip', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('items', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_signature', models.CharField(max_length=100)),
                ('payment_order_id', models.CharField(max_length=100)),
            ],
        ),
    ]
